Set CS register with non-deprecated function
phil-opp/blog_os pull request #1096
Opened 2022-03-18 03:42 UTC by Programatic

set_cs is deprecated and CS::set_reg is preferred. Update the blog to reflect this change according to the docs.

2022-03-19 09:15 UTC, ruhuang2001 requested changes

2022-03-19 09:15 UTC, ruhuang2001 commented on blog/content/edition-2/posts/06-double-faults/index.md
I think adding this change will be better.
```suggestion
// use x86_64::instructions::segmentation::set_cs;
use x86_64::instructions::segmentation::{CS, Segment};
```

2022-03-19 17:02 UTC, Programatic commented on blog/content/edition-2/posts/06-double-faults/index.md
Yup, forgot to change the use statements. Thanks for noticing.

2022-04-07 17:07 UTC, phil-opp commented
Thanks! If you have time (or someone else does), could you also send a PR to update the code in the `post-06` branch?

2022-04-07 17:07 UTC, merged

2022-04-08 04:20 UTC, ruhuang2001 commented
@phil-opp 
I send a PR #1099 to update in the `post-06` branch.