add ja file for post-07
phil-opp/blog_os pull request #1141
Opened 2022-09-17 13:44 UTC by shimomura1004

I translated post-07 to Japanese.

@JohnTitor and @woodyZootopia Could you review my translation?

2022-09-17 23:46 UTC, woodyZootopia requested changes
Since the section title has changed from `The 8259 PIC` to `8259 PIC`, you should change the internal link too.

2022-09-17 23:46 UTC, woodyZootopia commented on blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
> +[上述](#the-8259-pic)した図にある通り、タイマはプライマリの PIC の0番目の線を使います。これはタイマ割り込みは32番(0 + オフセットの32)の割り込みとして CPU に届くということです。32をハードコーディングする代わりに `InterruptIndex` enum に保存することにしましょう:
```suggestion
[上述](#8259-pic)した図にある通り、タイマはプライマリの PIC の0番目の線を使います。これはタイマ割り込みは32番(0 + オフセットの32)の割り込みとして CPU に届くということです。32をハードコーディングする代わりに `InterruptIndex` enum に保存することにしましょう:
```

2022-09-17 23:46 UTC, woodyZootopia commented on blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
> +[上述](#the-8259-pic)した図で見たように、キーボードはプライマリ PIC の1番目の線を使います。これはキーボード割り込みは33番(1 + オフセットの32)の割り込みとして CPU に届くということです。このインデックスを新たな `Keyboard` のヴァリアントとして `InterruptIndex` enum に追加します。enum ヴァリアントの値はデフォルトでは前の値
```suggestion
[上述](#8259-pic)した図で見たように、キーボードはプライマリ PIC の1番目の線を使います。これはキーボード割り込みは33番(1 + オフセットの32)の割り込みとして CPU に届くということです。このインデックスを新たな `Keyboard` のヴァリアントとして `InterruptIndex` enum に追加します。enum ヴァリアントの値はデフォルトでは前の値に1を足したもの、すなわち33になるので、値を明示的に指定する必要はありません。割り込みハンドラでは、`k` の文字を表示して割り込みコントローラに EOI 信号を送ります。
```

2022-09-18 00:04 UTC, woodyZootopia commented
Thank you for PR! Here are quick comments:
* Your article cannot be compiled because of the minor error above. I highly recommend you to install zola and compile the blog yourself (just `zola serve` in the `blog` directory). You can check if there is such a error very easily and visually see your progress :)
* Maybe it would be more readable if you put ` `（半角スペース）around `(` and `)`（半角カッコ）?
  e.g. 33番(1 + オフセットの32)の割り込み -> 33番 (1 + オフセットの32) の割り込み

I just skimmed through the article and am going to take a closer look later.

2022-09-18 02:24 UTC, shimomura1004 commented
Thank you for your comment! 
I've added spaces around parentheses and checked my translation with zola on my local environment.
I'm very sorry for pushing broken commit.

I look forward to hearing from you :)

By the way, "Zola Check" on github was failed because of dead link in other posts. (I wonder why my local build succeeded...)
Should I fix them with this PR or create another PR?

2022-09-18 03:30 UTC, shimomura1004 commented on blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
> +[上述](#the-8259-pic)した図で見たように、キーボードはプライマリ PIC の1番目の線を使います。これはキーボード割り込みは33番(1 + オフセットの32)の割り込みとして CPU に届くということです。このインデックスを新たな `Keyboard` のヴァリアントとして `InterruptIndex` enum に追加します。enum ヴァリアントの値はデフォルトでは前の値
I'm very sorry but I'm not familiar with github PR so I created other commit by myself...
Let me revert my commit.

2022-09-18 10:11 UTC, JohnTitor commented
> By the way, "Zola Check" on github was failed because of dead link in other posts. (I wonder why my local build succeeded...) Should I fix them with this PR or create another PR?

I'd prefer to create another one so that we don't have to wait for this PR to get that fix merged.

2022-09-18 13:59 UTC, woodyZootopia reviewed
Your translation was pretty good overall. I suggested a few possible changes, please take a look.

2022-09-18 23:26 UTC, shimomura1004 commented
Thank you so much for the review!
I'll check and apply your suggestion tonight.

2022-09-19 13:28 UTC, shimomura1004 commented on blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
> +`instructions::hlt` 関数はアセンブリ命令の[薄いラッパ][thin wrapper]です。この命令はメモリ安全性を損なわないので安全です。
ありがとうございます。修正いただいた訳のほうが適切と思いますのでこちらも適用しようと思いますが、"unsafe" の前後にスペースを入れたいと思います。

2022-09-19 13:45 UTC, shimomura1004 commented
@woodyZootopia
Thank you very much for your kind review! I've applied all your review comment.

@JohnTitor 
> I'd prefer to create another one so that we don't have to wait for this PR to get that fix merged.
I agree with you. Thanks!

2022-09-20 03:28 UTC, woodyZootopia commented
Thank you. Review finished on my side. Great work!

2022-09-20 07:04 UTC, phil-opp commented
Thanks a lot for this new translation @shimomura1004! And thanks to @woodyZootopia for reviewing!

Don't worry about the zola check error, we can fix that separately.

2022-09-20 07:13 UTC, closed without merging

2022-09-20 07:24 UTC, phil-opp commented
Merged manually in https://github.com/phil-opp/blog_os/commit/fe387b5fa6c29fb5287d58322e60ea22512445ca after some squashing. Unfortunately, I forgot to push the squashed history to this PR before pushing the merge commit, so GitHub decided to mark this PR as "closed" instead of "merged" now. I'm sorry about that!

I tried to force-push this branch back to bd15169 but this was no longer permitted.

The commits merged to the `main` branch still have the right author info, of course. See https://github.com/phil-opp/blog_os/commit/00b068a6eb6b551362702af425e38b078c872b2f and https://github.com/phil-opp/blog_os/commit/567ace4f8da87360bfd3e0193837c31860658d94.

2022-09-20 07:29 UTC, phil-opp commented
Published at https://os.phil-opp.com/ja/hardware-interrupts/

2022-09-20 11:19 UTC, shimomura1004 commented
No problem!  Thank you for merging :)