Translate post-12 to Japanese
phil-opp/blog_os pull request #977
Opened 2021-05-02 15:53 UTC by kahirokunn

The title says it all.
@JohnTitor Could you review the translation?

2021-05-02 19:56 UTC, JohnTitor commented
Thanks! I'll try to find some time by the following week. Meanwhile, could you drop 2182427 and open another PR so that this PR doesn't prevent that typo fix from being merged until reviewing is done?

2021-05-06 05:14 UTC, garasubo reviewed
Added a few advice.

2021-05-06 05:14 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このブログは[GitHub]でオープンに開発されています。何か問題や質問があれば、そこで課題を開いてください。また、[下部]にコメントを残すこともできます。この記事の完全なソースコードは、[`post-12`][post branch]ブランチにあります。
This part is common to other chapters. Could you replace this translation with that in other chapters?
At least, translating Github issue to "課題" sounds unnatural to me.

2021-05-06 05:14 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +この記事では、Rustの _cooperative multitasking_ と _async/await_ 機能について説明します。Rustのasync/await機能については、`Future` trait の設計、ステートマシンの変換、 _pinning_ などを含めて詳しく説明します。そして、非同期キーボードタスクと基本的なexecutorを作成することで、カーネルにasync/awa
* We may want to translate "cooperative multitasking" to "協調的マルチタスキング" or something like that.
* We've replaced _italic characters （イタリック体）_ with **bold（太字）** in other posts because italic style is not used for emphasizing in Japanese

2021-05-06 05:14 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +[_multitasking_]: https://en.wikipedia.org/wiki/Computer_multitasking
It would be nice to replace this with Japanese one if available.

2021-05-06 09:30 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +[_multitasking_]: https://en.wikipedia.org/wiki/Computer_multitasking
How about replacing everything with this?

before: multitasking
after: マルチタスク

2021-05-06 09:33 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このブログは[GitHub]でオープンに開発されています。何か問題や質問があれば、そこで課題を開いてください。また、[下部]にコメントを残すこともできます。この記事の完全なソースコードは、[`post-12`][post branch]ブランチにあります。
Corresponded 🙏

2021-05-06 09:37 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +この記事では、Rustの _cooperative multitasking_ と _async/await_ 機能について説明します。Rustのasync/await機能については、`Future` trait の設計、ステートマシンの変換、 _pinning_ などを含めて詳しく説明します。そして、非同期キーボードタスクと基本的なexecutorを作成することで、カーネルにasync/awa
Corresponded 🙏

2021-05-06 09:45 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +[_multitasking_]: https://en.wikipedia.org/wiki/Computer_multitasking
Corresponded 🙏

2021-05-06 09:51 UTC, kahirokunn commented
@garasubo Thx for your review! all Corresponded 🙏

2021-05-24 01:55 UTC, kahirokunn commented
@JohnTitor Hello 👀

2021-05-24 03:11 UTC, JohnTitor commented
Ah sorry, I wasn't feeling well in recent days. I'll check things by this week.

2021-05-24 09:36 UTC, woodyZootopia reviewed
Sorry to interrupt you guys, but may I help in review process like below? I'm hoping to alleviate the burden on @JohnTitor ...

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Saving State
I think "saving state" is not a technical term, so it can be translated
```suggestion
#### 状態の保存
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +タスクは任意の時点で中断されるため、計算の途中である可能性もあります。後で再開できるようにするために、OSは、タスクの[コールスタック]やすべてのCPUレジスタの値など、タスクの状態全体をバックアップする必要があります。この作業を[_context switch_]といいます。
```suggestion
タスクは任意の時点で中断されるため、計算の途中である可能性もあります。後で再開できるようにするために、OSは、タスクの[コールスタック]やすべてのCPUレジスタの値など、タスクの状態全体をバックアップする必要があります。この作業を[コンテキスト・スイッチ]といいます。
```
You chose to translate the word 'context switch' in the later part. Why not translate here too?

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +[_context switch_]: https://en.wikipedia.org/wiki/Context_switch
```suggestion
[コンテキスト・スイッチ]: https://en.wikipedia.org/wiki/Context_switch
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +タスクは任意の時点で中断されるため、計算の途中である可能性もあります。後で再開できるようにするために、OSは、タスクの[コールスタック]やすべてのCPUレジスタの値など、タスクの状態全体をバックアップする必要があります。この作業を[_context switch_]といいます。
```suggestion
タスクは任意の時点で中断されるため、計算の途中である可能性もあります。後で再開できるようにするために、OSは、タスクの[コールスタック]やすべてのCPUレジスタの値など、タスクの状態全体をバックアップする必要があります。この作業を[コンテキスト・スイッチ (context switch)] といいます。
```
This might be more explanatory

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Discussion
```suggestion
#### 議論
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +非協調的マルチタスクの欠点は、各タスクが独自のスタックを必要とすることです。共有スタックと比べると、タスクごとのメモリ使用量が多くなり、システム内のタスク数が制限されることが多くなります。また、タスクがレジスタの小さなサブセットしか使用していない場合でも、タスクが切り替わるたびにOSは常にCPUレジスタの状態を完全に保存しなければならないというデメリットもあります。
```suggestion
非協調的マルチタスクの欠点は、各タスクが独自のスタックを必要とすることです。共有スタックと比べると、タスクごとのメモリ使用量が多くなり、システム内のタスク数が制限されることが多くなります。また、タスクがレジスタのごく一部しか使用していない場合でも、タスクが切り替わるたびにOSは常にCPUレジスタの状態を完全に保存しなければならないというデメリットもあります。
```
The word サブセット may not sound familiar to Japanese.

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +協調的マルチタスクでは、実行中のタスクを任意のタイミングで強制的に停止させるのではなく、各タスクが自発的にCPUの制御を放棄するまで実行させます。これにより、例えば、I/O操作を待つ必要がある場合など、都合の良いタイミングでタスクを一時停止させることができます。
```suggestion
協調的マルチタスクでは、実行中のタスクを任意のタイミングで強制的に停止させるのではなく、各タスクが自発的にCPUの制御を放棄するまで実行させます。これにより、例えば、I/O操作を待つ必要がある場合など、都合の良いタイミングでタスクは一時停止することができます。
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +協調的マルチタスクと[asynchronous operations]を組み合わせるのが一般的です。asynchronous operations では、Operationが終了するまで待って、その間に他のタスクが実行できないようにする代わりに、操作がまだ終了していない場合は"not ready"というステータスを返します。この場合、待機中のタスクは yield operation を実行して他
```suggestion
協調的マルチタスクと[asynchronous operations]を組み合わせるのが一般的です。asynchronous operations では、操作 (operation) が終了するまで待って、その間に他のタスクが実行できないようにする代わりに、操作がまだ終了していない場合は"not ready"というステータスを返します。この場合、待機中のタスクは yield operation を実行して他のタスクを実行させることができます。
```
You translated operation as 操作 in the later part of this sentence. How about translating the former one like this?

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Saving State
```suggestion
#### 状態の保存
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Discussion
```suggestion
#### 議論
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +タスクは自分で一時停止のポイントを決めるので、OSがタスクの状態を保存しなくてよくなります。その代わり、継続するのに必要になる状態だけを保存することができ、その結果、パフォーマンスが向上しがちです。例えば、複雑な計算を終えたばかりのタスクは、中間結果を必要としないため、計算の最終結果をバックアップするだけで済むかもしれません。
```suggestion
タスクは自分で一時停止のポイントを決めるので、OSがタスクの状態を保存しなくてよくなります。その代わり、自分が停止する直前に継続するのに必要になる状態だけを保存することができ、その結果、パフォーマンスが向上することが多いです。例えば、複雑な計算を終えたばかりのタスクは、中間結果を必要としないため、計算の最終結果をバックアップするだけで済むかもしれません。
```

2021-05-24 09:36 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +言語でサポートされている協調タスクの実装では、一時停止する前にコールスタックの必要な部分をバックアップすることもできます。例えば、Rustのasync/awaitの実装では、まだ必要なすべてのローカル変数を、自動的に生成された構造体に格納しています（以下参照）。一時停止の前にコールスタックの関連部分をバックアップすることで、すべてのタスクが単一のコールスタックを共有することができ、タスクごとのメ
```suggestion
言語でサポートされている協調タスクの実装では、一時停止する前にコールスタックの必要な部分をバックアップすることもできることが多いです。例えば、Rustのasync/awaitの実装では、まだ必要なすべてのローカル変数を、自動的に生成された構造体に格納しています（後述）。一時停止の前にコールスタックの関連部分をバックアップすることで、すべてのタスクが単一のコールスタックを共有することができ、タスクごとのメモリ消費量が大幅に少なくなります。これにより、メモリ不足に陥ることなく、ほぼ任意の数の協調タスクを作成することができます。
```
you dropped 'often'?

2021-05-24 10:22 UTC, JohnTitor commented
Thanks @woodyZootopia! Could I leave the whole review to you or should I do reviewing since the "Async/Await in Rust" section?

2021-05-24 10:42 UTC, woodyZootopia commented
I'd be happy to review it all if @kahirokunn allows me to do so.

2021-05-27 00:17 UTC, woodyZootopia commented
@kahirokunn, could you allow me to review your translation? Or do you prefer @JohnTitor's review?

2021-05-27 03:46 UTC, kahirokunn commented
@woodyZootopia 

Sorry for the late reply.

We welcome reviews from anyone who can help us make this a better translation!

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +具体的にコンパイラがどのようなコードを生成するのかは実装依存ですが、`example` 関数に対してどのようなステートマシンが生成されうるかを想像することは、理解を助けることになります。異なる状態を表し、必要な変数を含む構造体はすでに定義されています。これらの構造体の上にステートマシンを作成するという方法があります。これらの構造体を[`enum`]構造体にまとめることができます:
```suggestion
具体的にコンパイラがどのようなコードを生成するのかは実装依存ですが、`example` 関数に対してどのようなステートマシンが生成されうるかを想像することは、理解を助けることになります。異なる状態を表し、必要な変数を含む構造体はすでに定義されています。これらの構造体の上にステートマシンを作成します。そのためには、これらの構造体を[`enum`]構造体にまとめるという方法があります:
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +コードの抜粋を少なくするために、各match armのコードを別々に紹介します。まず、`Start`の状態から始めましょう:
```suggestion
コードの抜粋が長大になるのを防ぐために、各match armのコードを別々に紹介します。まず、`Start`の状態から始めましょう:
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`match self {...}`Hogeステートメントはループで実行されるため、実行は次に `WaitingOnFooTxt` アームにジャンプします:
Why Hoge?

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +関数の冒頭ではステートマシンが `Start` 状態にあります。この例では、`example`関数のボディから最初の`.await`までのすべてのコードを実行します。`.await`の操作を処理するために、`self`ステートマシンの状態を`WaitingOnFooTxt`に変更し、`WaitingOnFooTxtState`構造体の構築を行います。
```suggestion
関数の冒頭ではステートマシンが `Start` 状態にあります。このとき、`example`関数の中身を最初の`.await`まですべて実行します。`.await`の操作を処理するために、`self`ステートマシンの状態を`WaitingOnFooTxt`に変更し、`WaitingOnFooTxtState`構造体の構築を行います。
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +コードの抜粋を少なくするために、各match armのコードを別々に紹介します。まず、`Start`の状態から始めましょう:
Also, "match arm" is translated as マッチアーム later.

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`foo_txt_future`の準備ができたら、その結果を`content`変数に代入して、引き続き`example`関数のコードを実行します。`content.len()`がstate構造体に保存されている`min_len`よりも小さければ、`bar.txt`ファイルが非同期に読み込まれます。`.await`の操作を再び状態の変化に変換し、今回は`WaitingOnBarTxt`の状態にしま
```suggestion
`foo_txt_future`の準備ができたら、その結果を`content`変数に代入して、引き続き`example`関数のコードを実行します。`content.len()`がstate構造体に保存されている`min_len`よりも小さければ、`bar.txt`ファイルが非同期に読み込まれます。`.await`の操作を再び状態の変化に変換し、今回は`WaitingOnBarTxt`の状態にします。ループ内で `match` を実行しているので、その後新しい状態のマッチアームに直接ジャンプし、そこで `bar_txt_future` がポーリングされます。
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`else`の分岐に入った場合、それ以上の`.await`操作は発生しません。関数の最後に到達して、`Poll::Ready`で包まれた`content`を返します。また、現在の状態を `End` に変更します。
```suggestion
`else`の分岐に入った場合、それ以上の`.await`操作は発生しません。関数の最後に到達したため、`Poll::Ready`でラップされた`content`を返します。また、現在の状態を `End` に変更します。
```
'wrap' has been translated as ラップ.

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`WaitingOnFooTxt`の状態と同様に、まず`bar_txt_future`をポーリングします。まだ保留中であれば、ループを抜けて `Poll::Pending` を返します。そうでなければ、`example`関数の最後の操作(つまり、`content`変数とfutureからの結果を連結します)を行います。ステートマシンを `End` 状態に更新して、`Poll::Ready` で包ま
```suggestion
`WaitingOnFooTxt`の状態と同様に、まず`bar_txt_future`をポーリングします。まだ保留中 (pending) であれば、ループを抜けて `Poll::Pending` を返します。そうでなければ、`example`関数の最後の操作（`content`変数とfutureからの結果の連結）を行います。ステートマシンを `End` 状態に更新して、`Poll::Ready` でラップされた結果を返します。
```
maybe this would be more informative

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +最後に、`End`ステートのコードは以下のようになります:
```suggestion
最後に、`End`状態のコードは以下のようになります:
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +これで、コンパイラが生成するステートマシンとその `Future` traitの実装がどのように見えるかがわかりました。実際には、コンパイラは異なる方法でコードを生成しています。 (一応、現在は[_generators_]をベースにした実装になっていますが、これはあくまでも実装の詳細です。)
```suggestion
コンパイラが生成するステートマシンとその `Future` traitの実装はこのようになっている**かもしれません**。実際には、コンパイラは異なる方法でコードを生成しています。 (一応、現在は[_generators_]をベースにした実装になっていますが、これはあくまでも実装の詳細です。)
```

2021-05-27 07:33 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +関数本体はステートマシンによって完全に実装されているので、関数に必要なことはステートマシンを初期化して返すことだけになります。このための生成コードは次のようになります:
```suggestion
関数本体はすべてステートマシンによって実装されたので、この関数がするべきことはステートマシンを初期化して返すことだけです。これを行う自動生成コードは次のようになります:
```

2021-05-27 07:51 UTC, woodyZootopia commented
@kahirokunn Could you apply the suggestions that seems reasonable to you? I want to know how much you accept my suggestions as I want to see how intensively I should give you suggestions for the later part in the article.

2021-05-27 11:21 UTC, kahirokunn commented
@woodyZootopia 

Thanks for the great suggestions!!!

I'm looking at it now!
I plan to commit to all of these!

2021-05-27 14:47 UTC, kahirokunn commented
@woodyZootopia 
Thanks for all the great corrections!
I've checked everything and COMMITTED everything!

2021-05-27 15:31 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +各ステートは、関数の異なるpause pointを表しています。 **"Start"** と **"End"** の状態は、関数の実行開始時と終了時を表しています。 **"Waiting on foo.txt"** の状態は、関数が最初の`async_read_file` の結果を待っていることを表しています。同様に、 **"Waiting on bar.txt"** 状態は、関数が2つ目の`a
Thx! Fixed!

2021-05-27 15:31 UTC, kahirokunn commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`match self {...}`Hogeステートメントはループで実行されるため、実行は次に `WaitingOnFooTxt` アームにジャンプします:
Sorry, Mistake! Fixed!

2021-05-28 00:47 UTC, woodyZootopia commented
@kahirokunn Thank you for accepting! I'll review the rest in the same way this weekend.

2021-05-28 02:14 UTC, kahirokunn commented
@woodyZootopia 
Thank you very much!
Once that work is done, I think we will be able to pass the quality test and release it to the internet!
I'm really looking forward to this translation being useful to people!

2021-05-28 05:35 UTC, woodyZootopia commented
@kahirokunn Could you translate the section titles and comments in the source code?

2021-05-29 02:36 UTC, woodyZootopia commented
@kahirokunn Also do not use different translations for the same word.
It seems you used both of
- combinator and コンビネータ
- コール　and 呼び出し
- match arm and マッチアーム
so please use either of these and make it all the same. I don't know which one you want to use.

2021-05-29 08:21 UTC, kahirokunn commented
@woodyZootopia 

> Could you translate the section titles and comments in the source code?

I have translated where I could to the best of my ability!

> Also, it would be better to avoid using different translations for the same word.
It seems you used both of

Fixed this point!

2021-05-29 08:21 UTC, kahirokunn commented
I did my best to translate the title into Japanese.
However, there were many parts that I did not know how to translate.
I left them in English.

2021-05-30 07:30 UTC, garasubo reviewed
Roughly reviewed untranslated parts

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +上記の破損を許した根本的な問題は、`Box<T>`によって、heapに割り当てられた値への`&mut T`参照を得ることができることです。この `&mut` 参照によって、 [`mem::replace`] や [`mem::swap`] などのメソッドを使って、heapに割り当てられた値を無効にすることが可能になります。この問題を解決するためには、自己参照構造体への `&mut` 参照が作成で
```suggestion
上記の破綻を許した根本的な問題は、`Box<T>`によって、ヒープに割り当てられた値への`&mut T`参照を得ることができることです。この `&mut` 参照によって、 [`mem::replace`] や [`mem::swap`] などのメソッドを使って、ヒープに割り当てられた値を無効にすることが可能になります。この問題を解決するためには、自己参照構造体への `&mut` 参照が作成できないようにする必要があります。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +pinning APIは、[`Pin`]ラッパー型と[`Unpin`]マーカーtraitという形で、`&mut T`問題に対する解決策を提供します。これらの型の背景にある考え方は、ラップされた値への `&mut` 参照を取得するために使用できる `Pin` のすべてのメソッド (例えば、[`get_mut`][pin-get-mut] や [`deref_mut`][pin-deref-mut]
```suggestion
ピン留めのAPIは、[`Pin`]ラッパー型と[`Unpin`]マーカートレイトという形で、`&mut T`問題に対する解決策を提供します。これらの型の背景にある考え方は、ラップされた値への `&mut` 参照を取得するために使用できる `Pin` のすべてのメソッド (例えば、[`get_mut`][pin-get-mut] や [`deref_mut`][pin-deref-mut]) を `Unpin` trait にゲートすることです。`Unpin` トレイトは[**自動トレイト**]であり、明示的にオプトアウトした型を除くすべての型に対して自動的に実装されます。自己参照構造体は `Unpin` をオプトアウトすることで、`Pin<Box<T>>` 型から `&mut T` を得る (安全な) 方法がありません。その結果、それらの内部の自己参照が有効であることが保証されます。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +そこで、[`PhantomPinned`]型の2つ目の `_pin` フィールドを追加することでオプトアウトします。この型はゼロサイズのマーカー型で、`Unpin` trait を実装**しない**ようにすることだけが目的です。[auto traits][_auto trait_]の仕組み上、`Unpin`ではない1つのフィールドがあれば、構造体全体が`Unpin`をオプトアウトするのに十分です
```suggestion
そこで、[`PhantomPinned`]型の2つ目の `_pin` フィールドを追加することでオプトアウトします。この型はゼロサイズのマーカー型で、`Unpin` trait を実装**しない**ようにすることだけが目的です。[自動トレイト][_auto trait_]の仕組み上、`Unpin`ではない1つのフィールドがあれば、構造体全体が`Unpin`をオプトアウトするのに十分です。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +第二のステップは、例題の `Box<SelfReferential>` 型を `Pin<Box<SelfReferential>>` 型に変更することです。これを行う最も簡単な方法は、heapに割り当てられた値を作成するために、[Box::new`]ではなく、[Box::pin`]関数を使用することです:
```suggestion
第二のステップは、例題の `Box<SelfReferential>` 型を `Pin<Box<SelfReferential>>` 型に変更することです。これを行う最も簡単な方法は、ヒープに割り当てられた値を作成するために、[Box::new`]ではなく、[Box::pin`]関数を使用することです:
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Executor
```suggestion
#### エクゼキュータ
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +executorの目的は、ある種の `spawn` メソッドを使って、独立したtaskとしてfutureを生成することです。そうすることで executor はすべてのfutureが完了するまでポーリングする責任を担うのです。すべてのfutureを中央で管理することの大きな利点は、あるfutureが `Poll::Pending` を返すたびに、executorが別のfutureに切り替えること
```suggestion
エクゼキュータの目的は、ある種の `spawn` メソッドを使って、独立したタスクとしてfutureを生成することです。そうすることでエクゼキュータはすべてのfutureが完了するまでポーリングする責任を担うのです。すべてのfutureを中央で管理することの大きな利点は、あるfutureが `Poll::Pending` を返すたびに、エクゼキュータが別のfutureに切り替えることができることです。このようにして、非同期の処理が並行して実行され、CPUをずっと忙しくしておけます。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +多くのexecutorの実装では、システムが複数のCPUコアを持っている場合にそれを生かすことができます。これらの実装では、十分な作業量があればすべてのコアを利用できる[thread pool]を作成したり、[work stealing]などの手法を用いてコア間の負荷を分散させたりします。また、低レイテンシーとメモリオーバーヘッドに最適化した、組み込みシステム用の特別なexecutorの実装もあ
```suggestion
多くのエクゼキュータの実装では、システムが複数のCPUコアを持っている場合にそれを生かすことができます。これらの実装では、十分な作業量があればすべてのコアを利用できる[スレッドプール]を作成したり、[ワークスチール]などの手法を用いてコア間の負荷を分散させたりします。また、低レイテンシーとメモリオーバーヘッドに最適化した、組み込みシステム用の特別なエクゼキュータの実装もあります。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Waker
ウェイカー

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +waker APIの背景にある考え方は、特別な[`Waker`]型が[`Context`]型にラップされて、`poll`の各呼び出しに渡されるというものです。この `Waker` 型はexecutorによって作成され、非同期タスクがその(部分的な)完了を知らせるために使用することができます。その結果、executorは以前に `Poll::Pending` を返したfutureに対して、対応する
```suggestion
ウェイカー APIの背景にある考え方は、特別な[`Waker`]型が[`Context`]型にラップされて、`poll`の各呼び出しに渡されるというものです。この `Waker` 型はexecutorによって作成され、非同期タスクがその(部分的な)完了を知らせるために使用することができます。その結果、エクゼキュータは以前に `Poll::Pending` を返したfutureに対して、対応するウェイカーから通知されるまで `poll` を呼び出す必要がありません。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +## Implementation
```suggestion
## 実装
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +### Task
```suggestion
### タスク
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- `dyn`キーワードは、`Box`に[_trait object_]を格納することを示しています。これはfuture上のメソッドが[_動的にディスパッチされる_]ことを意味しており、`Task` 型に異なる型のfutureを格納することが可能になります。各 `async fn` はそれぞれ異なる型を持っている一方で、複数の異なるタスクを作成できるようにしたいので、これは重要です。
```suggestion
- `dyn`キーワードは、`Box`に[**トレイトオブジェクト**]を格納することを示しています。これはfuture上のメソッドが[**動的にディスパッチされる**]ことを意味しており、`Task` 型に異なる型のfutureを格納することが可能になります。各 `async fn` はそれぞれ異なる型を持っている一方で、複数の異なるタスクを作成できるようにしたいので、これは重要です。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +この関数は、出力型が `()` の任意のfutureを受け取り、[`Box::pin`] 関数を使ってそれをメモリに固定します。そして、ボックス化されたfutureを `Task` 構造体でラップして返します。ここで `'static` lifetime が必要なのは、返された `Task` が任意の時間だけ生き続けることができるので、futureもその時間だけ有効である必要があるからです。
```suggestion
この関数は、出力型が `()` の任意のfutureを受け取り、[`Box::pin`] 関数を使ってそれをメモリに固定します。そして、ボックス化されたfutureを `Task` 構造体でラップして返します。ここで `'static` ライフタイムが必要なのは、返された `Task` が任意の時間だけ生き続けることができるので、futureもその時間だけ有効である必要があるからです。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +また、`poll`メソッドを追加して、executorがstored futureをポーリングできるようにしましょう:
```suggestion
また、`poll`メソッドを追加して、エクゼキュータが格納されたfutureをポーリングできるようにしましょう:
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Dummy Waker
```suggestion
#### ダミーウェイカー
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +##### A Dummy `RawWaker`
```suggestion
##### ダミーの`RawWaker`
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Scancode Queue
```suggestion
#### スキャンコードキュー
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +##### `crossbeam` Crate
```suggestion
##### `crossbeam`クレート
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +これらの問題を防ぐためには、`push`操作にmutexやアロケートを必要としないqueueの実装が必要です。このようなqueueは、要素のpushとpopにロックフリーの[atomic operations]を用いることで実装できます。この方法では、`&self`の参照だけを必要とする`push`と`pop`の操作を作成することができ、したがって、mutexなしで使用することができます。`pu
```suggestion
これらの問題を防ぐためには、`push`操作にミューテックスやアロケートを必要としないキューの実装が必要です。このようなキューは、要素のpushとpopにロックフリーの[アトミックな操作]を用いることで実装できます。この方法では、`&self`の参照だけを必要とする`push`と`pop`の操作を作成することができ、したがって、mutexなしで使用することができます。`push`での割り当てを避けるために、あらかじめ割り当てられた固定サイズのバッファ上にキューを作ります。これにより、キューは **bound** (すなわち最大の長さを持つ)ことになりますが、実際には、queueの長さに妥当な上限を定義することが可能な場合が多いので、これは大きな問題ではありません。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このようなqueueを正しく効率的に実装するのは非常に難しいので、既存の、よくテストされた実装を使うことをお勧めします。concurrent programmingのために様々なmutex-free型を実装している人気のあるRustプロジェクトの1つに[`crossbeam`]があります。このプロジェクトでは、[`ArrayQueue`]という名前の型が提供されており、今回のケースでまさに必要な
```suggestion
このようなキューを正しく効率的に実装するのは非常に難しいので、既存の、よくテストされた実装を使うことをお勧めします。並行プログラミングのために様々なmutex-free型を実装している人気のあるRustプロジェクトの1つに[`crossbeam`]があります。このプロジェクトでは、[`ArrayQueue`]という名前の型が提供されており、今回のケースでまさに必要なものです。そして幸運なことに、この型はアロケーションをサポートする `no_std` クレートと完全に互換性があります。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Scancode Stream
```suggestion
#### スキャンコードストリーム
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +##### `Stream` Trait
```suggestion
##### `Stream` トレイト
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このコードは、この記事で修正する前の[keyboard interrupt handler]にあったコードと非常によく似ています。唯一の違いは、I/O portからscancodeを読み込むのではなく、`ScancodeStream`からscancodeを取得することです。このために、まず新しい `Scancode` ストリームを作成し、次に [`StreamExt`] traitが提供する [
```suggestion
このコードは、この記事で修正する前の[キーボードの割り込みハンドラ]にあったコードと非常によく似ています。唯一の違いは、I/Oポートからスキャンコードを読み込むのではなく、`ScancodeStream`からスキャンコードを取得することです。このために、まず新しい `Scancode` ストリームを作成し、次に [`StreamExt`]トレイトが提供する [`next`] メソッドを繰り返し使用して、ストリーム内の次の要素に解決する `Future` を取得します。これに `await` 演算子を用いることで、futureの結果を非同期的に待ちます。
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Task Id
```suggestion
#### タスクID
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### Spawning Tasks
```suggestion
#### タスクの生成
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +##### `Wake` Trait
```suggestion
##### `Wake`トレイト
```

2021-05-30 07:30 UTC, garasubo commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### IdleならSleepする
```suggestion
#### アイドルならスリープする
```

2021-05-30 11:55 UTC, woodyZootopia commented
It's taking longer than I thought. Please wait a little more.

2021-06-03 09:42 UTC, woodyZootopia commented
@kahirokunn by the way, you can commit multiple suggestions at once. Try that next time.

2021-06-05 12:24 UTC, kahirokunn commented
@woodyZootopia commit multiple suggestions at once feature is awesome!
thx!
what's next? 👀

2021-06-05 12:31 UTC, woodyZootopia reviewed
@kahirokunn Reviewing the rest of the article is finally done! Sorry to keep you waiting this long...

Some comments below:

Your translation was pretty good overall.

By the way, it seems like you've used machine translators in some parts.
Machine translators are helpful as they can create natural translations, but they are incomplete especially when translating jargon. They need a careful double-check, and I don't recommend using machine translators if you can't do that by yourself.

If you have trouble translating, please leave it not to the machine translators, but to the reviewers. Leave comments in the translation (e.g. `ここの翻訳よくわからんかった`), ask questions here, or even leave that part in English. I would rather appreciate that way, as I can pay closer attention to the part you had difficulties with.

Anyway, thanks for your translation! I'm looking forward to publishing this article.

Also, Did @sozysozbot help in the translation? Huge thanks to you too!

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このメソッドは `run_ready_tasks` 関数をループで呼び出すだけです。理論的には、`tasks`マップが空になったときにこの関数から戻ることもできますが、`keyboard_task`が終了しないので、このようなことは起こらず、単純な`loop`で十分です。この関数は決して戻りませんので、`!`という戻り値の型を使って、コンパイラにこの関数が[diverging]であることを示しま
```suggestion
このメソッドは `run_ready_tasks` 関数の呼び出しをループするだけです。理論的には、`tasks`マップが空になったときにこの関数からリターンすることもできますが、`keyboard_task`が終了しないのでそれは起こらず、よって単純な`loop`で十分です。この関数は決してリターンしませんので、`!`という戻り値の型を使って、コンパイラにこの関数が[発散する (diverging) ][diverging]ことを示します。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +    // […] init_heap、test_mainを含む初期化ルーチン
```suggestion
    // init_heap、test_mainを含む初期化ルーチンを省略
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +必要なのは import と型名を変更するだけです。関数 `run` は分岐しているとマークされているので、コンパイラはこの関数が決して戻らないことを認識し、`kernel_main` 関数の最後に `hlt_loop` を呼び出す必要がなくなりました。
```suggestion
必要なのは、インポート部（`use`のところ）と型名を変更することだけです。関数 `run` は発散する関数となっているので、コンパイラはこの関数が決してリターンしないことを認識し、そのため`kernel_main` 関数の最後に `hlt_loop` を呼び出す必要はもうありません。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +ここで、`cargo run`を使ってカーネルを実行すると、キーボード入力が正常に動作することがわかります:
```suggestion
ここで、`cargo run`を使ってカーネルを実行すると、キーボード入力が変わらず正常に動作することがわかります:
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +しかし、QEMUのCPU使用率は一向に向上しませんでした。その理由は、CPUをずっとbusy状態にしているからです。タスクが再び起こされるまでポーリングすることはなくなりましたが、busy loopで`task_queue`をチェックしています。この問題を解決するには、やるべき仕事がなくなったらCPUをスリープさせる必要があります。
```suggestion
しかし、QEMUのCPU使用量は全く減っていません。その理由は、CPUをずっとbusy状態にしているからです。タスクが再び起こされるまでポーリングすることはなくなりましたが、`task_queue`をチェックし続けるbusy loop（忙しないループの意）に入っているのです。この問題を解決するには、やるべき仕事がなくなったらCPUをスリープさせる必要があります。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### アイドルならスリープする
```suggestion
#### 何もすることがない (idle) ならスリープする
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +基本的な考え方は、`task_queue`が空になったときに[`hlt` instruction]を実行するというものです。この命令は、次の割り込みが来るまでCPUをスリープ状態にします。割り込みが入るとCPUがすぐに活動を再開するので、割り込みハンドラが`task_queue`にpushされたときにも直接反応できるようになっています。
```suggestion
基本的な考え方は、`task_queue`が空になったときに[`hlt`命令]を実行するというものです。この命令は、次の割り込みが来るまでCPUをスリープ状態にします。割り込みが入るとCPUがすぐに活動を再開するので、割り込みハンドラが`task_queue`にpushされたときにも直接反応できるようになっています。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`sleep_if_idle`は、`task_queue`が空になるまでループする`run_ready_tasks`の直後に呼び出されるので、queueを再度チェックする必要はないと思われるかもしれません。しかし、`run_ready_tasks` が戻ってきた直後にハードウェア割り込みが発生する可能性があるため、`sleep_if_idle` 関数が呼ばれた時点でqueueに新しいタスクがある
```suggestion
`sleep_if_idle`は、`task_queue`が空になるまでループする`run_ready_tasks`の直後に呼び出されるので、キューを再度チェックする必要はないと思われるかもしれません。しかし、`run_ready_tasks` がリターンしてきた直後にハードウェア割り込みが発生する可能性があるため、`sleep_if_idle` 関数が呼ばれた時点ではキューに新しいタスクがあるかもしれません。キューがまだ空であった場合のみ、[`x86_64`]クレートが提供する[`instructions::hlt`]ラッパー関数を介して`hlt`命令を実行することで、CPUをスリープさせます。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +競合状態を避けるために、`task_queue` が空であるかどうかを確認する前に、割り込みを無効にします。空いていれば、[`enable_and_hlt`]関数を使用して割り込みを有効にし、単一のアトミック操作としてCPUをスリープさせます。queueが空でない場合は、`run_ready_tasks` が戻ってきた後に、割り込みがタスクを起動したことを意味します。その場合は、再び割り込みを有
```suggestion
競合状態を避けるために、`task_queue` が空であるかどうかを確認する前に、割り込みを無効にします。空いていれば、[`enable_and_hlt`]関数を使用して、単一のアトミック操作として割り込みを有効にしCPUをスリープさせます。キューが空でない場合は、`run_ready_tasks` がリターンしてきた後に、割り込みがタスクを起動したことを意味します。その場合は、再び割り込みを有効にして、`hlt`を実行せずにすぐに実行を継続します。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +これで、実行することがないときには、executorが適切にCPUをスリープ状態にします。再び`cargo run`を使ってカーネルを実行すると、QEMUプロセスのCPU使用率が大幅に低下していることがわかります。
```suggestion
これで、実行することがないときには、executorが適切にCPUをスリープ状態にするようになりました。再び`cargo run`を使ってカーネルを実行すると、QEMUプロセスのCPU使用率が大幅に低下していることがわかります。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +#### 可能な拡張機能
```suggestion
#### 考えられる機能拡張
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- **Scheduling**: 現在、我々は[`VecDeque`]型を使用して、先入れ先出し(FIFO)戦略を`task_queue`に実装しています。これはしばしば **round robin** スケジューリングとも呼ばれます。この戦略は、すべてのワークロードにとって最も効率的であるとは限りません。例えば、レイテンシーが重要なタスクや、I/Oを大量に行うタスクを優先させることは意味があ
```suggestion
- **スケジューリング**: 現在、我々は[`VecDeque`]型を使用して、先入れ先出し(FIFO)戦略を`task_queue`に実装しています。これはしばしば **ラウンドロビン (round robin)** スケジューリングとも呼ばれます。この戦略は、すべてのワークロードにとって最も効率的であるとは限りません。例えば、レイテンシーが重要なタスクや、I/Oを大量に行うタスクを優先させることは意味があるかもしれません。詳しくは、[_Operating Systems: Three Easy Pieces_]の[スケジューリングの章][scheduling chapter]や、[スケジューリングに関するWikipediaの記事][scheduling-wiki]をご覧ください。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- **Task Spawning**: 現在、私たちの `Executor::spawn` メソッドは `&mut self` の参照を必要とするため、`run` メソッドを開始した後は利用できません。この問題を解決するには、追加の `Spawner` 型を作成します。この型は、ある種のqueueをexecutorと共有し、タスク自身の中からタスクを作成することができます。このqueueは、例
```suggestion
- **タスクの発生 (spawn)**: 現在、私たちの `Executor::spawn` メソッドは `&mut self` の参照を必要とするため、`run` メソッドを開始した後は利用できません。この問題を解決するには、追加で `Spawner` 型を作成します。この型は、ある種のキューをexecutorと共有し、タスク自身の中からタスクを作成することができます。このキューには、例えば `task_queue` を直接使用することもできますし、executorが実行ループの中でチェックする別のキューを使用することもできます。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- **Utilizing Threads**: まだスレッドのサポートはしていませんが、次の投稿で追加する予定です。これにより、executorの複数のインスタンスを異なるスレッドで起動することが可能になります。このアプローチの利点は、他のタスクが同時に実行できるため、長時間実行するタスクによって課せられる遅延を減らすことができることです。また、この方法では、複数のCPUコアを利用することもで
```suggestion
- **スレッドを活用する**: まだスレッドのサポートはしていませんが、次の投稿で追加する予定です。これにより、executorの複数のインスタンスを異なるスレッドで起動することが可能になります。このアプローチの利点は、複数のタスクが同時に実行できるため、長時間実行するタスクによって課せられる遅延を減らすことができることです。また、この方法では、複数のCPUコアを利用することもできます。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- **Load Balancing**: スレッドサポートを追加した場合、すべてのCPUコアが利用されるように、executor間でどのようにタスクを分配するかが重要になります。このための一般的なテクニックは、[_work stealing_]です。
```suggestion
- **負荷の分配**: スレッドをサポートするようにした場合、すべてのCPUコアが利用されるように、executor間でどのようにタスクを分配するかが重要になります。このための一般的なテクニックは、[_work stealing_]です。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +舞台裏では、コンパイラが async/await コードを **state machine** に変換し、各 `.await` オペレーションが可能な街状態に対応するようにします。プログラムに関する知識を活用することで、コンパイラは各待ち状態の最小限の状態のみを保存することができ、その結果、タスクあたりのメモリ消費量は非常に小さくなります。一つの課題は、生成されたステートマシンに **自己参照*
```suggestion
舞台裏では、コンパイラが async/await コードを **ステートマシン** に変換し、各 `.await` オペレーションが可能な待ち状態に対応するようにします。プログラムに関する知識を活用することで、コンパイラは各待ち状態に必要な最小限の状態のみを保存することができ、その結果、タスクあたりのメモリ消費量は非常に小さくなります。一つの課題は、生成されたステートマシンに **自己参照**構造体が含まれている可能性があることです。例えば、非同期関数のローカル変数が互いに参照している場合などです。ポインタの無効化を防ぐために、Rustは`Pin`型を用いて、futureが最初にポーリングされた後は、メモリ内で移動できないようにしています。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +私たちの**実装**では、まず、`Waker`型を全く使わずに、busy loopですべてのspawnされたタスクをポーリングする非常に基本的なexecutorを作成しました。次に、非同期のキーボードタスクを実装することで、waker通知の利点を示しました。このタスクは、`crossbeam`クレートが提供するミューテックスフリーの`ArrayQueue`型を使って、静的な`SCANCODE_Q
```suggestion
私たちの**実装**では、まず、`Waker`型を全く使わずに、busy loopですべてのspawnされたタスクをポーリングする非常に基本的なexecutorを作成しました。次に、非同期のキーボードタスクを実装することで、waker通知の利点を示しました。このタスクは、`crossbeam`クレートが提供する`ArrayQueue`というmutexを使わない型を使って、静的な`SCANCODE_QUEUE`を定義します。キーボード割り込みハンドラは、キーの入力を直接処理する代わりに、受信したすべてのスキャンコードをキューに入れ、登録されている `Waker` を起こして、新しい入力が利用可能であることを通知します。受信側では、`ScancodeStream`型を作成して、キュー内の次のスキャンコードに変化する`Future`を提供しています。これにより、非同期の `print_keypresses` タスクを作成することができました。このタスクは、キュー内のスキャンコードを解釈して出力するために async/await を使用します。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +キーボードタスクのwaker通知を利用するために、新しい `Executor` 型を作成しました。この型は、ready タスク用に `Arc` 共有の `task_queue` を使用します。 私たちは`TaskWaker`型を実装し、起こされたタスクのIDを直接この`task_queue`にpushし、それをexecutorが再びポーリングするようにしました。また、実行可能なタスクがないときに
```suggestion
キーボードタスクのwaker通知を利用するために、新しい `Executor` 型を作成しました。この型は、準備のできたタスクに `Arc` で共有された `task_queue` を使用します。 私たちは`TaskWaker`型を実装し、起こされたタスクのIDを直接この`task_queue`にpushし、それをexecutorが再びポーリングするようにしました。また、実行可能なタスクがないときに電力を節約するために、`hlt`命令を用いてCPUをスリープさせる機能を追加しました。最後に、マルチコアへの対応など、executorの拡張の可能性について述べました。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +async/waitを使うことで、カーネルで協調的マルチタスクを基本的にサポートできるようになりました。協調的マルチタスクは非常に効率的ですが、個々のタスクの実行時間が長すぎるために他のタスクの実行が妨げられ、遅延の問題が発生します。このため、カーネルに非協調的マルチタスクのサポートを追加することは理にかなっています。
```suggestion
async/waitを使うことで、カーネルで基本的な協調的マルチタスクをサポートできるようになりました。協調的マルチタスクは非常に効率的ですが、個々のタスクが長く実行しすぎる場合、他のタスクの実行が妨げられ、遅延の問題が発生します。このため、カーネルに非協調的マルチタスクのサポートを追加することは理にかなっています。
```

2021-06-05 12:31 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +次回は、非協調的マルチタスクの最も一般的な形態である **thread** を紹介します。スレッドは、長時間実行されるタスクの問題を解決するだけでなく、将来的に複数のCPUコアを利用したり、信頼できないユーザープログラムを実行したりするための準備にもなります。
```suggestion
次回は、非協調的マルチタスクの最も一般的な形態である **スレッド** を紹介します。スレッドは、長時間実行されるタスクの問題を解決するだけでなく、将来的に複数のCPUコアを利用したり、信頼できないユーザープログラムを実行したりするための準備にもなります。
```

2021-06-08 02:40 UTC, kahirokunn commented
I'll do that next time! 🙏 

By the way, the changes piled up so much that when I tried to look at the suggestions from Diff's place, Github went to 502, so I was in trouble... 😢

2021-06-08 03:52 UTC, woodyZootopia commented
Oh, I didn't expect that to happen. I'm sorry but I don't know any solution as that never happened before...
Maybe the best way you can do is to click the
```
169 hidden coversations
Load more...
```
above and commit them one by one until my suggestions shrink enough to be loaded at once.

2021-06-10 02:13 UTC, kahirokunn commented
@woodyZootopia 
I committed each of the commit suggestions one by one, and when I opened the Diff tab at about 130, it stopped being 502 and I was able to batch commit!
I've committed all of them!
Thank you so much for all your detailed reviews!

2021-06-10 03:12 UTC, woodyZootopia commented
Review is complete on my side.
@JohnTitor Do you see any point to fix? If not, I think it's ready to be published.

2021-06-10 03:29 UTC, woodyZootopia requested changes

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +これらの問題を防ぐためには、`push`操作にmutexやアロケートを必要としないキューの実装が必要です。このようなキューは、要素のpushとpopにロックフリーの[atomic operations]を用いることで実装できます。この方法では、`&self`の参照しか必要としない`push`と`pop`の操作を作成することができ、したがって、mutexなしで使用することができます。`push`の
```suggestion
これらの問題を防ぐためには、`push`操作にmutexやアロケートを必要としないキューの実装が必要です。このようなキューは、要素のpushとpopにロックを使用しない[atomic operations]を用いることで実装できます。この方法では、`&self`の参照しか必要としない`push`と`pop`の操作を作成することができ、したがって、mutexなしで使用することができます。`push`の際のアロケートを避けるために、あらかじめ割り当てられた固定サイズのバッファ上にキューを作ります。これにより、キューは **有界** （最大の長さを持つという意味）になりますが、実際には、キューの長さに妥当な上限を定義することが可能な場合が多いので、これは大きな問題ではありません。
```

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +このようなキューを正しく効率的に実装するのは非常に難しいので、既存の、よくテストされた実装を使うことをお勧めします。concurrent programmingのために様々なmutex-free型を実装している人気のあるRustプロジェクトの1つに[`crossbeam`]があります。このプロジェクトでは、[`ArrayQueue`]という名前の型が提供されており、これは今回のケースでまさに必要
```suggestion
このようなキューを正しく効率的に実装するのは非常に難しいので、既存の、よくテストされた実装を使うことをお勧めします。並行プログラミングのために様々なmutexを使用しない型を実装している人気のあるRustプロジェクトの1つに[`crossbeam`]があります。このプロジェクトでは、[`ArrayQueue`]という名前の型が提供されており、これは今回のケースでまさに必要なものです。そして幸運なことに、この型はアロケーションをサポートしている `no_std` のクレートと完全に互換性があります。
```

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +予想通り、`cargo run` を使ってプロジェクトを実行しても、キーの入力が画面に表示されなくなりました。代わりに、キーを押すたびにスキャンコード キューが初期化されていないという警告が表示されます。
```suggestion
予想通り、`cargo run` を使ってプロジェクトを実行しても、キーの入力が画面に表示されなくなりました。代わりに、キーを押すたびにスキャンコードキューが初期化されていないという警告が表示されます。
```

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +非同期タスクがスキャンコードを利用できるようにするためには、次のステップとしてキューから次のスキャンコードを取り出そうとする `poll` のようなメソッドを実装します。これは、私たちの型に[`Future`]特性を実装するべきであるように聞こえますが、これはここではうまくいきません。問題は、`Future` trait は単一の非同期値を抽象化するだけであり、`Poll` メソッドが `Pol
```suggestion
非同期タスクがスキャンコードを利用できるようにするためには、次のステップとしてキューから次のスキャンコードを取り出そうとする `poll` のようなメソッドを実装します。これは、私たちの型に[`Future`]特性を実装するべきであるように聞こえますが、これはここではうまくいきません。問題は、`Future` trait は単一の非同期値を抽象化するだけであり、`Poll` メソッドが `Poll::Ready` を返した後は二度と呼び出されないことを期待しているということです。しかし、私たちのスキャンコードキューは複数の非同期値を含んでいるので、ポーリングし続けても問題ありません。
```

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +その答えは、チェックの前にCPUの割り込みを無効にし、`hlt`命令と一緒にアトミックに再度有効にすることです。この方法では、その間に発生するすべての割り込みが `hlt` 命令の後に遅延されるため、wake-upsが失敗することはありません。この方法を実装するには、[`x86_64`]クレートが提供する[`interrupts::enable_and_hlt`][`enable_and_hlt
```suggestion
その答えは、チェックの前にCPUの割り込みを無効にし、`hlt`命令と一緒にアトミックに再度有効にすることです。この方法では、その間に発生するすべての割り込みが `hlt` 命令の後に遅延されるため、wakeupが失敗することはありません。この方法を実装するには、[`x86_64`]クレートが提供する[`interrupts::enable_and_hlt`][`enable_and_hlt`]関数を使用します。
```

2021-06-10 03:29 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +前回と同様に、まず [`OnceCell::try_get`] 関数を使用して、初期化されたスキャンコード キューへの参照を取得します。そして、キューからの `pop` を試みてみて、成功したら `Poll::Ready` を返します。このようにすれば、キューが空でないときにwakerを登録することによるパフォーマンスのオーバーヘッドを回避することができます。
```suggestion
前回と同様に、まず [`OnceCell::try_get`] 関数を使用して、初期化されたスキャンコードキューへの参照を取得します。そして、キューからの `pop` を試みてみて、成功したら `Poll::Ready` を返します。このようにすれば、キューが空でないときにwakerを登録することによるパフォーマンスのオーバーヘッドを回避することができます。
```

2021-06-10 07:38 UTC, woodyZootopia reviewed
I skimmed through the whole article again to refine it.
@kahirokunn I found several minor corrections so please approve if they seem reasonable.

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +Futureのポーリングに`TaskWaker`型を使うには、まずこれを[`Waker`]インスタンスに変換する必要があります。これは [`Future::poll`] メソッドが引数として [`Context`] インスタンスを取るためで、このインスタンスは `Waker` 型からしか構築できません。これは [`RawWaker`] 型の実装を提供することによって可能ですが、代わりに `Arc
```suggestion
Futureのポーリングに`TaskWaker`型を使うには、まずこれを[`Waker`]インスタンスに変換する必要があります。これは [`Future::poll`] メソッドが引数として [`Context`] インスタンスを取り、このインスタンスは `Waker` 型からしか構築できないためです。これは [`RawWaker`] 型の実装を提供することによって可能ですが、代わりに `Arc` ベースの [`Wake`][wake-trait] trait を実装し、標準ライブラリが提供する [`From`] の実装を使用して `Waker` を構築する方が、よりシンプルで安全でしょう。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +`Waker` 型は、`Wake` traitを実装したすべての `Arc` ラッピングされた値からの [`From`] 変換をサポートしているので、`Executor::run_ready_tasks` メソッドで必要となる `TaskWaker::new` 関数を実装することができます:
```suggestion
`Waker` 型は、`Wake` traitを実装したすべての `Arc` でラップされた値からの [`From`] 変換をサポートしているので、`Executor::run_ready_tasks` メソッドで必要となる `TaskWaker::new` 関数を実装することができます:
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +基本的な考え方は、`task_queue`が空になったときに[`hlt`命令]を実行するというものです。この命令は、次の割り込みが来るまでCPUをスリープ状態にします。割り込みが入るとCPUがすぐに活動を再開するので、割り込みハンドラが`task_queue`にpushされたときにも直接反応できるようになっています。
```suggestion
基本的な考え方は、`task_queue`が空になったときに[`hlt`命令][`hlt` instruction]を実行するというものです。この命令は、次の割り込みが来るまでCPUをスリープ状態にします。割り込みが入るとCPUがすぐに活動を再開するので、割り込みハンドラが`task_queue`にpushされたときにも直接反応できるようになっています。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +- **スレッドを活用する**: まだスレッドのサポートはしていませんが、次の投稿で追加する予定です。これにより、executorの複数のインスタンスを異なるスレッドで起動することが可能になります。このアプローチの利点は、複数のタスクが同時に実行できるため、長時間実行するタスクによって課せられる遅延を減らすことができることです。また、この方法では、複数のCPUコアを利用することもできます。
```suggestion
- **スレッドを活用する**: まだスレッドのサポートはしていませんが、次の投稿で追加する予定です。これにより、複数のexecutorのインスタンスを異なるスレッドで起動することが可能になります。このアプローチの利点は、複数のタスクが同時に実行できるため、長時間実行するタスクによって課せられる遅延を減らすことができることです。また、この方法では、複数のCPUコアを利用することもできます。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +この記事ではまず、**マルチタスク**について紹介し、実行中のタスクを定期的に強制的に中断させる**非協調的**マルチタスクと、タスクが自発的にCPUの制御を放棄するまで実行させる**協調的**マルチタスクの違いを説明しました。
```suggestion
この記事ではまず、**マルチタスク**について紹介し、実行中のタスクを定期的に強制的に中断させる**非協調的**マルチタスクと、タスクが自発的にCPUの制御を放棄するまで実行させてやる**協調的**マルチタスクの違いを説明しました。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +次に、Rustがサポートする**async/await**がどのようにして協調的マルチタスクの言語レベルの実装を提供しているかを調べました。Rustは、非同期タスクを抽象化するポーリングベースの`Future` traitをベースにして実装しています。async/awaitを使うと、通常の同期コードとほぼ同じようにfutureを扱うことができます。違いは、非同期関数が再び `Future` を返
```suggestion
次に、Rustがサポートする**async/await**がどのようにして協調的マルチタスクの言語レベルの実装を提供しているかを調べました。Rustは、非同期タスクを抽象化するポーリングベースの`Future` traitをベースにして実装しています。async/awaitを使うと、通常の同期コードとほぼ同じようにfutureを扱うことができます。違いは、非同期関数が再び `Future` を返すことで、それを実行するためにはどこかの時点でこの`Future`をexecutorに追加する必要があります。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +舞台裏では、コンパイラが async/await コードを **ステートマシン** に変換し、各 `.await` オペレーションが可能な待ち状態に対応するようにします。プログラムに関する知識を活用することで、コンパイラは各待ち状態に必要な最小限の状態のみを保存することができ、その結果、タスクあたりのメモリ消費量は非常に小さくなります。一つの課題は、生成されたステートマシンに **自己参照**構
```suggestion
舞台裏では、コンパイラが async/await コードを **ステートマシン** に変換し、各 `.await` オペレーションが可能な待ち状態に対応するようにします。対象のプログラムに関する知識を活用することで、コンパイラは各待ち状態に必要な最小限の状態のみを保存することができ、その結果、タスクあたりのメモリ消費量は非常に小さくなります。一つの課題は、生成されたステートマシンに **自己参照**構造体が含まれている可能性があることです。例えば、非同期関数のローカル変数の一方が他方を参照している場合などです。ポインタの無効化を防ぐために、Rustは`Pin`型を用いて、futureが最初にポーリングされた後は、メモリ内で移動できないようにしています。
```

2021-06-10 07:38 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +### Wakerサポート付きのExecutor
```suggestion
### WakerをサポートするExecutor
```

2021-06-10 11:51 UTC, woodyZootopia commented
@kahirokunn did you apply all of my suggestions? If so, review is end on my side.
@JohnTitor @garasubo Do you have anything to fix before publishing?
If they don't, let's proceed to publication.

2021-06-10 11:52 UTC, woodyZootopia commented
@kahirokunn by the way, did you ask @sozysozbot of the permission to be a co-translator? How did he contribute to the translation?

2021-06-10 14:23 UTC, kahirokunn commented
@woodyZootopia
Thx!
I applied all!
@sozysozbot gave me a lot of reviews on Discord!

2021-06-10 19:29 UTC, JohnTitor commented
I'm not sure if I have some time to review so feel free to go ahead without me.

2021-06-11 01:38 UTC, kahirokunn commented
@woodyZootopia I asked @sozysozbot on Discord, and he allowed!

2021-06-11 06:38 UTC, garasubo commented
It looks almost OK, but one thing we may want to fix is to translate "trait" to "トレイト". In some part, this word was translated, but there are still some untranslated sentences.
But I don't mind publishing without fixing this.

2021-06-11 08:15 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +ピン留めのAPIは、[`Pin`]ラッパー型と[`Unpin`]マーカートレイトという形で、`&mut T`問題に対する解決策を提供します。これらの型の背景にある考え方は、（`Pin`によって）ラップされた値への `&mut` 参照を取得するために使用できる `Pin` のすべてのメソッド (例えば、[`get_mut`][pin-get-mut] や [`deref_mut`][pin-der
```suggestion
ピン留めのAPIは、[`Pin`]ラッパー型と[`Unpin`]マーカーtraitという形で、`&mut T`問題に対する解決策を提供します。これらの型の背景にある考え方は、（`Pin`によって）ラップされた値への `&mut` 参照を取得するために使用できる `Pin` のすべてのメソッド (例えば、[`get_mut`][pin-get-mut] や [`deref_mut`][pin-deref-mut]) を `Unpin` trait に限定することです。`Unpin` traitは[**自動trait**][_auto trait_]であり、明示的に使用しないよう宣言した型を除くすべての型に対して自動的に実装されます。自己参照構造体は `Unpin` を使用しないようにさせることで、`Pin<Box<T>>` 型から `&mut T` を得る (安全な) 方法を無くすことができます。その結果、それらの内部の自己参照が有効であることが保証されます。
```

2021-06-11 08:15 UTC, woodyZootopia commented on blog/content/edition-2/posts/12-async-await/index.ja.md
> +[`PhantomPinned`]型の2つ目のフィールド `_pin` を追加することで`Unpin`を使用しないようにします。この型はゼロサイズのマーカー型で、`Unpin` trait を実装**しない**ようにするためだけに置かれています。[自動トレイト][_auto trait_]の仕組み上、`Unpin`ではないフィールドが1つでもあれば、構造体全体が`Unpin`を使用しないようにな
```suggestion
[`PhantomPinned`]型の2つ目のフィールド `_pin` を追加することで`Unpin`を使用しないようにします。この型はゼロサイズのマーカー型で、`Unpin` trait を実装**しない**ようにするためだけに置かれています。[自動trait][_auto trait_]の仕組み上、`Unpin`ではないフィールドが1つでもあれば、構造体全体が`Unpin`を使用しないようになります。
```

2021-06-11 08:16 UTC, woodyZootopia commented
Applying these unifies トレイト to trait.
@kahirokunn Choose one of these.

2021-06-14 03:27 UTC, kahirokunn commented
@woodyZootopia I like trait!

2021-06-14 03:31 UTC, woodyZootopia commented
Ok. I believe we can go ahead. 
@phil-opp Could you merge this PR?

2021-06-14 08:09 UTC, phil-opp commented
Awesome! Thanks so much for the translation @kahirokunn and all the others for the detailed review!

2021-06-14 08:09 UTC, merged

2021-06-14 08:12 UTC, phil-opp commented
The post is now available at <https://os.phil-opp.com/ja/async-await/>.

2021-06-14 08:48 UTC, kahirokunn commented
Thx a lot! 😭